#!/bin/sh
# Keep npm child scripts on Node 26 even if ancestor node_modules contains node.
PATH=/mnt/c/Users/USER/projects/aidev/state/runs/2026-10-08-215834-hunter-improve/toolchain/node_modules/node/bin:$PATH
export PATH
exec /bin/sh "$@"
